// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNyVgQNleOP-IlPZz9yp81QoBt8c3SIw',
    appId: '1:595261039583:web:1c44f81803a2ef4b651a6a',
    messagingSenderId: '595261039583',
    projectId: 'health-app-efa06',
    authDomain: 'health-app-efa06.firebaseapp.com',
    storageBucket: 'health-app-efa06.firebasestorage.app',
    measurementId: 'G-1SSSK176QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe8TUh5J8InAvWQBhs9GMr098AXxWPcNc',
    appId: '1:595261039583:android:cc51cbb139bf2da9651a6a',
    messagingSenderId: '595261039583',
    projectId: 'health-app-efa06',
    storageBucket: 'health-app-efa06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQEp3JMgoRFujwWdmZg8UVqsuMZJ6pfKg',
    appId: '1:595261039583:ios:14acd1dc9d13204e651a6a',
    messagingSenderId: '595261039583',
    projectId: 'health-app-efa06',
    storageBucket: 'health-app-efa06.firebasestorage.app',
    iosBundleId: 'com.example.fitnessHealthUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQEp3JMgoRFujwWdmZg8UVqsuMZJ6pfKg',
    appId: '1:595261039583:ios:14acd1dc9d13204e651a6a',
    messagingSenderId: '595261039583',
    projectId: 'health-app-efa06',
    storageBucket: 'health-app-efa06.firebasestorage.app',
    iosBundleId: 'com.example.fitnessHealthUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaNyVgQNleOP-IlPZz9yp81QoBt8c3SIw',
    appId: '1:595261039583:web:4b1506c6038eb708651a6a',
    messagingSenderId: '595261039583',
    projectId: 'health-app-efa06',
    authDomain: 'health-app-efa06.firebaseapp.com',
    storageBucket: 'health-app-efa06.firebasestorage.app',
    measurementId: 'G-FWRN3ZZKM8',
  );
}
